#!/usr/bin/env bash
# install nginx and serve
sudo apt -y update
sudo apt -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.nginx-debian.html
service nginx start
# ssh ubuntu@100.24.238.196 "sudo apt -y update && sudo apt -y install nginx && sudo su -c 'echo Hello World! > /var/www/html/index.nginx-debian.html'"
