#!/usr/bin/env bash
# install nginx and serve and configure redirect
sudo apt -y update
sudo apt -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.nginx-debian.html
new_str="location /redirect_me {\n\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;}"
old="# include snippets/snakeoil.conf;"
sed -i "s/$old/$new_str" /etc/nginx/sites-available/default
service nginx start
