#!/usr/bin/env bash
# install nginx and serve and configure redirect
sudo apt -y update
sudo apt -y install nginx
ufw allow 'Nginx HTTP'
sudo su -c "echo 'Hello World!' > /var/www/html/index.nginx-debian.html"
SERVER_CONF=\
"server {
  listen 80 default_server;
  listen [::]:80 default_server;
  root /var/www/html;
  index index.html index.htm index.nginx-debian.html;
  server_name _;
  location / {
    try_files $uri $uri/ =404;
  }
  location /redirect_me {
    return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
  }
}"
sudo su -c "echo -e SERVER_CONF > /etc/nginx/sites-available/default"
service nginx start
