#!/usr/bin/env bash
# install nginx and serve and configure redirect.
sudo apt -y update
sudo apt -y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custome_404.html
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/ permanent;' /etc/nginx/sites-available/default
sudo sed -i "40i error_page 404 /custome_404.html;" /etc/nginx/sites-available/default
sudo service nginx restart
