#!/usr/bin/env bash
# configure web-02 and update web-01
sudo apt -y update
sudo apt -y install nginx
ufw allow 'Nginx HTTP'
f='$'
l='ri'
server="map \$hostname \$var1 {
    ~*01\$ web-01;
    default web-02;
	}
	server {
        listen 80 default_server;
        listen [::]:80 default_server;
        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;
        server_name _;
        location / {
                try_files ${f}r${l} ${f}r${l}/ =404;
                add_header X-Served-By $var1;
        }
}"
echo -e "$server" > /etc/nginx/sites-available/default
sudo systemctl restart nginx
