#!/usr/bin/env bash
# configure web-02 and update web-01
sudo apt -y update
sudo apt -y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custome_404.html

server_cnf="
server {
        listen 80 default_server;
        listen [::]:80 default_server;
        add_header X-Served-By $HOSTNAME;
        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;
        
        location /redirect_me {
                return 301 http://www.youtube.com/;
        }
        error_page 404 /custome_404.html;
        location /404 {
                internal;
        }
}"
echo "$server_cnf" > /etc/nginx/sites-available/default
sudo systemctl restart nginx
