#!/usr/bin/env bash
# configure web-02 and update web-01
sudo apt-get -y update
sudo apt-get -y install haproxy

echo "
backend my_backend
	listen load_balancer
	bind *:80
	balance roundrobin
	server 367979-web-01 192.168.1.1:80 check
	server 367979-web-02 192.168.1.2:80 check
" >> /etc/haproxy/haproxy.cfg
sudo systemctl start haproxy
