#!/usr/bin/env bash
# configure web-02 and update web-01
sudo apt-get update
sudo apt-get install haproxy -y

echo "
frontend myfrontend
	bind *:80
	mode http
        default_backend mybackend
backend mybackend
	balance roundrobin
	server 367979-web-01 192.168.1.1:80 check
	server 367979-web-02 192.168.1.2:80 check
" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
