#!/usr/bin/env bash
# script that manage process
if (( $1 == "start" ))
then
	./manage_my_process $
	mkdir -p /var/run/
	echo $$ >> /var/run/my_process.pid
	echo "manage_my_process started"
elif (( $1 == "stop" ))
then
	kill -INT "$(pgrep -x manage_my_process)"
	rm /var/run/my_process.pid
	echo "manage_my_process stopped"
elif (( $1 == "restart" ))
then
	kill -INT "$(pgrep -x manage_my_process)"
        rm /var/run/my_process.pid
	./manage_my_process $
	echo $$ >> /var/run/my_process.pid
	echo "manage_my_process restarted"
else
	echo "Usage: manage_my_process {start|stop|restart}"
fi
