#!/usr/bin/env bash
# Bash script that displays the content of the file /etc/passwd.
while read -r line; do
	username=$(echo "$line" | cut -d ':' -f 1)
	group_id=$(echo "$line" | cut -d ':' -f 4)
	dir=$(echo "$line" | cut -d ':' -f 6)
	shell=$(echo "$line" | cut -d ':' -f 7)
	user_id=$(echo "$line" | cut -d ':' -f 3)
	passcode=$(echo "$line" | cut -d ':' -f 2)
	user_id_info=$(echo "$line" | cut -d ':' -f 5)
	echo "The user $username is part of the $group_id gang,"\
	"lives in $dir and rides $shell."\
	"$user_id's place is protected by the passcode $passcode,"\
	"more info about the user here: $user_id_info"
done < "/etc/passwd"
