#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
hour=0
while [[ $hour -le 12 ]]; do
	echo "Hour: $hour"
	mint=1
	while [[ $mint -le 59 ]]; do
		echo $mint
		(( mint+=1 ))
	done
	(( hour+=1 ))
done
