#!/usr/bin/env bash
# Firewalls can not only filter requests, they can also forward them.
conf="*nat
:PREROUTING ACCEPT [0:0]
-A PREROUTING -p tcp --dport 80 -j REDIRECT --to-port 8080
COMMIT
"
echo "$conf" >> /etc/ufw/before.rules
sudo service ufw restart
